### ISSUE TITLE
Missing Mantic Minotaur Mascot

### ISSUE THREAD

**Issue by anthonydillon** [canonical/design.ubuntu.com#300]
**What kind of resource or asset are you looking for?**

The wallpaper and marketing resources for the latest release of Ubuntu 23.10.

**Is it related to any specific product? Where is it going to be used?**

Ubuntu

**Have you seen or used it before?**

There are versions in blogs that people are copying from but it is not clear it's the right marketing material.

**Additional context**

We provide Luna Lobster wallpaper here: https://design.ubuntu.com/resources

**Comment by anasereijo** [comment]
It can be found here: https://drive.google.com/drive/folders/1dKGvGgFp4ymGNBPU6LRScfBm4KuwIn2c
